info:
  title: Joseph Liao
  author: Joseph Liao
  subtitle: Network Engineer | SDE
  url: https://github.com/Joseph-ljx

defaults:
  favicon: /images/logo_3.png
  logo: /images/logo_3.png
  avatar: /images/avatar.png

home_banner:
  enable: true
  style: fixed   
  image:
    light: /images/background_2.jpeg
    dark: /images/background_2.jpeg
  title: Joseph Liao
  subtitle:
    text:
      - "Current Network & Automation Engieer @ CTA"
      - "Open to collaborations!"
  text_color:
    light: "#ffffff"
    dark: "#d1d1b6"
  text_style:
    title_size: 3.5rem
    subtitle_size: 1.8rem
  social_links:
    enable: true
    links:
      github: https://github.com/Joseph-ljx
      fa-brands fa-linkedin: https://www.linkedin.com/in/joseph-liao/
      fa-brands fa-kaggle: https://www.kaggle.com/ljx02263

navbar:
  auto_generate: false
  auto_hide: false
  links:
    EXPERIENCE:
      path: /archives/
      icon: fa-regular fa-folder-open
    # TRAVEL:
    #   icon: fa-solid fa-bookmark 
    #   path: /bookmarks/
    RESUME:
      icon: fa-regular fa-user
      path: /about/
    LINK:
      icon: fa-regular fa-link
      submenus:
        LINKEDIN: https://www.linkedin.com/in/joseph-liao/
        GITHUB: https://github.com/Joseph-ljx

articles:
  word_count: 
    enable: false
    min2read: false
  author_label: 
    list: ["Network Engineer"]

search:
  enable: true
  preload: true

plugins:
  link_handle:
    enable: false
  aplayer:  
        enable: true
        type: fixed
        autoplay: true
        audios:
            - name: Passionfruit
              artist: Drake
              url: /music/BGM_2.mp3
              cover: /images/BGM.png
          
inject:
  enable: true
  head:
    - <link rel="stylesheet" href="/css/nav-home-banner.css">
  footer:
    - <script defer src="/js/nav-home-banner.js"></script>

comment:
  enable: false
